### PR TITLE
Added BlueMicro firmware files for use of a nice!nano

### PR DESCRIPTION
**Pull request by omalleh**
Hi Moses,
Hope you are well.

I have created the required files to generate BlueMicro firmware for a nice!nano when used with your litl board.
The files in the source folder can be used with https://github.com/jpconstantineau/BlueMicro_Builder 
Which will allow you to create a .uf2 file for the nice!nano.
The default layout isn't perfect, as I haven't figured out how to get the space bars to do double duty as a layer switch.
However the code and example firmware is functional as is.

I would also like to build ZMK firmware for your board and a nice!nano, but this is taking me quite some time to fully understand the ZMK documentation...

I'm not hugely familiar with the process of using git and creating pull requests, so I hope this is okay!

Cheers,
Tom

### CODE REVIEW

**Comment by omalleh** [comment]
Sorry, I should have also noted that I combined all of the wonderful QMK files you provided into a folder within the firmware folder, then added mine in a separate folder called BlueMicro. Just to help keep things neatly organized.

**Comment by mohoyt** [comment]
Hey Tom! 

Thank you so much for sending a PR! Super nice of you to work on this and contribute! Are you using a Nice!nano with your Litl? How do you like it? And how's the battery life? I haven't used one yet, but it's on my list of controllers to try! 

Your PR looks great from a read over of the firmware so I will approve it. Looking forwards to seeing how you get on with ZMK. 

Thanks, 
Moses

**Comment by omalleh** [comment]
Quite alright, it's the way it should work! I wanted to get your great Litl board working with a nice!nano and wanted to share the outcome.

I haven't had much time with the board yet to really comment on battery life, however I love the flexibility on my desk using wireless with a board the size of Litl.

ZMK will be sometime into the new year now as I'm away with family for the festive season. I think my next bit of tinkering will be to get an oled display up and running on BlueMicro, I'll make another pull request when I've completed that too, if that's okay?

**Comment by mohoyt** [comment]
Great to hear! Intrigued to see what the battery life will be like with an OLED running as I imagine they're not super power efficient (the makers of the Nice!Nano even make an e-ink one, the Nice!View, for potentially this reason).

No stress on any of the PRs, looking forward to seeing what you do! Have an excellent Christmas/New year!

**Pull request merged**
